org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.16.9

fabric_version=0.140.2+1.21.11

mod_version=1.2.0
maven_group=net.hoggielibrary
archives_base_name=hoggielibrary

java_version=21
